spring.datasource.url=jdbc:mysql://localhost:3306/smartcart
spring.datasource.username=root
spring.datasource.password=Yazhini@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081